version: '3.8'

services:
  mdas-api-g6:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - rabbitmq
    environment:
      - SPRING_RABBITMQ_HOST=rabbitmq
    networks:
      - rabbit-network

  rabbitmq:
    image: "rabbitmq:3-alpine"
    ports:
      - "5672:5672"   # Default RabbitMQ port
    networks:
      - rabbit-network

networks:
  rabbit-network:
    driver: bridge
