version: '3.8'

services:
  rabbitmq:
    container_name: mdas-api-RabbitMQ
    image: "rabbitmq:3-alpine"
    ports:
      - "5672:5672"
    networks:
      - rabbit-network

  app:
    container_name: mdas-api-Adria-Manero
    build: .
    stdin_open: true
    tty: true
    ports:
      - "8080:8080"
    depends_on:
      - rabbitmq
    environment:
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_PORT=5672
    networks:
      - rabbit-network

networks:
  rabbit-network:
    driver: bridge
